### ISSUE TITLE
Browser crashes with larger dxf files

### ISSUE THREAD

**Issue by alsonp** [gdsestimating/three-dxf#30] opened 2019-08-06 09:53 UTC
My browser crashed when I tried to render dxf file with size of 15MB. What could be the fix to it? Any help would be appreciated.

**Comment by Serthys** [comment] 2019-08-06 09:56
Might be related to #5.
From my experience using the library, the problem is the size in memory of the threejs objects, there's no way arround that.

**Comment by bzuillsmith** [comment] 2019-08-06 14:16
Yes. Same issue as #5. The problem is that the parser is synchronous and when a script runs too long, browsers kill it. We need it to be async, but then you have to track state and the parser gets way more complicated.

I've been wondering if async generators can somehow solve this problem but I've not had time lately to work on it.

**Comment by bzuillsmith** [comment] 2019-10-13 23:51
Closing since it is a duplicate of #5

**Closed by bzuillsmith** 2019-10-13 23:51 UTC
